"""Tests for Markdown session export."""
from __future__ import annotations

import pytest

from jarvis.tools.markdown_export import _format_content, session_to_markdown


class TestFormatContent:
    def test_string_returned_as_is(self):
        assert _format_content("hello world") == "hello world"

    def test_list_with_text_block(self):
        blocks = [{"type": "text", "text": "my answer"}]
        assert "my answer" in _format_content(blocks)

    def test_list_with_tool_use_block(self):
        blocks = [{"type": "tool_use", "name": "web_search", "input": {"query": "RLHF"}}]
        result = _format_content(blocks)
        assert "web_search" in result
        assert "RLHF" in result
        assert "```json" in result

    def test_list_with_tool_result_block(self):
        blocks = [{"type": "tool_result", "content": "Found 5 results"}]
        result = _format_content(blocks)
        assert "Found 5 results" in result

    def test_non_string_converted(self):
        assert isinstance(_format_content(42), str)

    def test_empty_list_returns_empty(self):
        result = _format_content([])
        assert result == ""


class TestSessionToMarkdown:
    def _simple_messages(self):
        return [
            {"role": "user", "content": "What is RLHF?"},
            {"role": "assistant", "content": "RLHF stands for Reinforcement Learning from Human Feedback."},
        ]

    def test_returns_string(self):
        assert isinstance(session_to_markdown(self._simple_messages()), str)

    def test_contains_title_heading(self):
        md = session_to_markdown(self._simple_messages(), title="My research")
        assert "# My research" in md

    def test_auto_title_from_first_user_message(self):
        md = session_to_markdown(self._simple_messages())
        assert "# What is RLHF?" in md

    def test_user_heading_present(self):
        md = session_to_markdown(self._simple_messages())
        assert "## You" in md

    def test_jarvis_heading_present(self):
        md = session_to_markdown(self._simple_messages())
        assert "## JARVIS" in md

    def test_message_content_included(self):
        md = session_to_markdown(self._simple_messages())
        assert "Reinforcement Learning from Human Feedback" in md

    def test_session_id_in_document(self):
        md = session_to_markdown(self._simple_messages(), session_id="abc-123")
        assert "abc-123" in md

    def test_footer_present(self):
        md = session_to_markdown(self._simple_messages())
        assert "Generated by JARVIS" in md

    def test_separator_lines_present(self):
        md = session_to_markdown(self._simple_messages())
        assert "---" in md

    def test_empty_messages_no_crash(self):
        md = session_to_markdown([])
        assert isinstance(md, str)

    def test_metadata_in_footer(self):
        md = session_to_markdown(
            self._simple_messages(), metadata={"model": "sonnet", "turns": "2"}
        )
        assert "model: sonnet" in md

    def test_tool_calls_in_fenced_block(self):
        messages = [
            {"role": "assistant", "content": [
                {"type": "tool_use", "name": "web_search", "input": {"query": "test"}}
            ]},
        ]
        md = session_to_markdown(messages)
        assert "```json" in md
        assert "web_search" in md

    def test_message_count_in_document(self):
        md = session_to_markdown(self._simple_messages())
        assert "Messages:** 2" in md
