"""Render a session's message history as a Markdown document.

The output is designed for sharing research: clean headings, tool call
details in fenced code blocks, and a metadata footer.
"""
from __future__ import annotations

import json
import re
import time
from datetime import datetime


def _format_content(content) -> str:
    """Render a message content field (str or list of blocks) as Markdown."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict):
                if block.get("type") == "text":
                    parts.append(block.get("text", ""))
                elif block.get("type") == "tool_use":
                    tool_name = block.get("name", "tool")
                    tool_input = block.get("input", {})
                    parts.append(
                        f"*[Tool: {tool_name}]*\n```json\n{json.dumps(tool_input, indent=2)}\n```"
                    )
                elif block.get("type") == "tool_result":
                    result_content = block.get("content", "")
                    if isinstance(result_content, list):
                        result_content = "\n".join(
                            b.get("text", "") for b in result_content if isinstance(b, dict)
                        )
                    parts.append(f"*[Tool result]*\n```\n{result_content}\n```")
        return "\n\n".join(parts)
    return str(content)


def session_to_markdown(
    messages: list[dict],
    session_id: str = "",
    title: str = "",
    metadata: dict | None = None,
) -> str:
    """Convert a session message list to a Markdown document string.

    Args:
        messages:   List of {role, content} dicts.
        session_id: Session identifier for the footer.
        title:      Optional title; auto-generated from first user message if empty.
        metadata:   Optional extra metadata dict for the footer.

    Returns:
        Markdown string.
    """
    lines: list[str] = []

    # ── Title ─────────────────────────────────────────────────────────────────
    if not title:
        first_user = next(
            (m for m in messages if m.get("role") == "user"), None
        )
        if first_user:
            raw = str(first_user.get("content", ""))
            title = raw[:80].split("\n")[0].strip()
        else:
            title = "JARVIS Session"

    lines.append(f"# {title}\n")

    # ── Metadata header ────────────────────────────────────────────────────────
    if session_id:
        lines.append(f"**Session:** `{session_id}`  ")
    lines.append(f"**Exported:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  ")
    lines.append(f"**Messages:** {len(messages)}\n")
    lines.append("---\n")

    # ── Messages ───────────────────────────────────────────────────────────────
    role_labels = {
        "user": "## You",
        "assistant": "## JARVIS",
        "system": "## System",
        "tool": "## Tool result",
    }

    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")

        label = role_labels.get(role, f"## {role.capitalize()}")
        lines.append(label)
        lines.append("")

        rendered = _format_content(content)
        lines.append(rendered)
        lines.append("")

    # ── Footer ─────────────────────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("*Generated by JARVIS*")
    if metadata:
        extra = ", ".join(f"{k}: {v}" for k, v in metadata.items())
        lines.append(f"*{extra}*")

    return "\n".join(lines)
