from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class ReportInput:
    title: str
    content: str
    topic: str
    sources: list[str] = field(default_factory=list)


def handle_save_report(tool_input: dict, reports_dir: Path) -> str:
    try:
        inp = ReportInput(
            title=tool_input["title"],
            content=tool_input["content"],
            topic=tool_input["topic"],
            sources=tool_input.get("sources") or [],
        )
        reports_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        slug = inp.topic.lower().replace(" ", "-")[:40]
        filename = reports_dir / f"{timestamp}-{slug}.md"
        header = f"# {inp.title}\n\n*Generated by JARVIS on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n---\n\n"
        body = inp.content
        if inp.sources:
            seen: set[str] = set()
            unique = [s for s in inp.sources if s not in seen and not seen.add(s)]  # type: ignore[func-returns-value]
            sources_section = "\n\n## Sources\n\n" + "\n".join(f"- {s}" for s in unique)
            body = body + sources_section
        filename.write_text(header + body, encoding="utf-8")
        return f"Report saved to: {filename}"
    except Exception as e:
        return f"ERROR: save_report failed — {e}"


def handle_update_report(tool_input: dict, reports_dir: Path) -> str:
    """Append a new section to an existing report file."""
    try:
        filename_str = tool_input["filename"]
        section_title = tool_input["section_title"]
        section_content = tool_input["section_content"]
        target = reports_dir / filename_str
        if not target.exists():
            return f"ERROR: report not found — {filename_str}"
        addition = f"\n\n## {section_title}\n\n*Updated by JARVIS on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n{section_content}"
        with target.open("a", encoding="utf-8") as f:
            f.write(addition)
        return f"Report updated: {target}"
    except Exception as e:
        return f"ERROR: update_report failed — {e}"


SCHEMA: dict = {
    "name": "save_report",
    "description": (
        "Save a completed research report to disk as a markdown file. "
        "Call this when you have finished synthesizing research and are ready to persist it."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "Full title of the report.",
            },
            "content": {
                "type": "string",
                "description": "Complete markdown body of the report (excluding the title heading).",
            },
            "topic": {
                "type": "string",
                "description": "Short topic slug used for the filename, e.g. 'rlhf' or 'transformer-architecture'.",
            },
            "sources": {
                "type": "array",
                "items": {"type": "string"},
                "description": "List of source URLs cited in this report. Will be appended as a ## Sources section.",
            },
        },
        "required": ["title", "content", "topic"],
    },
}

UPDATE_SCHEMA: dict = {
    "name": "update_report",
    "description": (
        "Append a new section to an existing saved report. "
        "Use this to add follow-up findings without creating a duplicate report."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "filename": {
                "type": "string",
                "description": "Filename of the existing report (basename only, e.g. '20240101-120000-rlhf.md').",
            },
            "section_title": {
                "type": "string",
                "description": "Title of the new section to append.",
            },
            "section_content": {
                "type": "string",
                "description": "Markdown content of the new section.",
            },
        },
        "required": ["filename", "section_title", "section_content"],
    },
}
