"""Plugin: generate_tool — self-improvement loop entry point.

Claude calls this to scaffold a new plugin tool. It creates a template file
in tools/plugins/ that Claude can then implement and test using run_command.

Workflow:
  1. generate_tool(tool_name="fetch_stock", description="...", hint="...")
  2. Claude reviews the created draft file (uses read_url or browse for docs)
  3. Claude implements the handler (edits the file via run_command)
  4. Claude tests with: run_command("python -c '...'")
  5. Claude renames _draft.py → .py when satisfied
  6. Restart loads the plugin automatically
"""
from __future__ import annotations

import re
from pathlib import Path

_TEMPLATE = '''\
"""Plugin: {name} — {description}

Generated by JARVIS self-improvement loop.
Implement handle() then rename this file from {name}_draft.py to {name}.py
"""
from __future__ import annotations


def handle(tool_input: dict) -> str:
    """Plugin handler. Must never raise — return "ERROR: ..." strings instead."""
    try:
        # TODO: implement {name}
        # Hint: {hint}
        raise NotImplementedError("Replace this with the real implementation.")
    except NotImplementedError as e:
        return f"ERROR: {name} not yet implemented — {{e}}"
    except Exception as e:
        return f"ERROR: {name} failed — {{e}}"


SCHEMA: dict = {{
    "name": "{name}",
    "description": "{description}",
    "input_schema": {{
        "type": "object",
        "properties": {{
            "input": {{
                "type": "string",
                "description": "Primary input for {name}.",
            }}
        }},
        "required": ["input"],
    }},
}}
'''


def handle(tool_input: dict) -> str:
    try:
        name = tool_input.get("tool_name", "").strip().lower().replace(" ", "_").replace("-", "_")
        description = tool_input.get("description", "").strip()
        hint = tool_input.get("implementation_hint", "Use Python stdlib or requests.").strip()

        if not name or not description:
            return "ERROR: tool_name and description are required."
        if not re.match(r"^[a-z][a-z0-9_]{1,49}$", name):
            return "ERROR: tool_name must be 2–50 lowercase letters/numbers/underscores."

        plugins_dir = Path(__file__).parent
        draft_path = plugins_dir / f"{name}_draft.py"
        final_path = plugins_dir / f"{name}.py"

        if draft_path.exists():
            return f"ERROR: {draft_path.name} already exists. Delete it or choose a different name."
        if final_path.exists():
            return f"ERROR: {final_path.name} already exists."

        draft_path.write_text(
            _TEMPLATE.format(name=name, description=description, hint=hint),
            encoding="utf-8",
        )

        return (
            f"Scaffold created: {draft_path}\n\n"
            f"Next steps:\n"
            f"1. Implement handle() in the draft file\n"
            f"2. Test: run_command(\"python -m pytest {draft_path} -x\") or use run_command\n"
            f"3. Activate: run_command(\"mv {draft_path} {final_path}\")\n"
            f"4. Restart JARVIS — plugin is auto-loaded from tools/plugins/"
        )
    except Exception as e:
        return f"ERROR: generate_tool failed — {e}"


SCHEMA: dict = {
    "name": "generate_tool",
    "description": (
        "Scaffold a new JARVIS plugin. Creates a template in tools/plugins/ "
        "for you to implement and test. This is the self-improvement loop — "
        "use it to expand JARVIS's capabilities without restarting."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "tool_name": {
                "type": "string",
                "description": "Snake_case name, e.g. 'fetch_stock_price'.",
            },
            "description": {
                "type": "string",
                "description": "What the tool does (used in its schema description).",
            },
            "implementation_hint": {
                "type": "string",
                "description": "How to implement it, e.g. 'Call Yahoo Finance REST API with requests'.",
            },
        },
        "required": ["tool_name", "description"],
    },
}
